# Netlify configuration file for MIDI Drum Remapper
# This file provides build settings and redirects for proper SPA routing

[build]
  # Since this is a static site, no build command is needed
  publish = "/"

# Handle 404 errors correctly by redirecting to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://cdn.skypack.dev;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.skypack.dev https://pagead2.googlesyndication.com https://www.googletagmanager.com https://www.google-analytics.com https://www.googletagservices.com https://ep2.adtrafficquality.google;
      style-src 'self' 'unsafe-inline';
      connect-src 'self' https://www.google-analytics.com https://ep1.adtrafficquality.google https://ep2.adtrafficquality.google https://pagead2.googlesyndication.com https://tpc.googlesyndication.com;
      frame-src 'self' https://googleads.g.doubleclick.net https://tpc.googlesyndication.com https://ep2.adtrafficquality.google https://www.google.com;
      img-src 'self' data: https://pagead2.googlesyndication.com https://googleads.g.doubleclick.net https://www.google-analytics.com https://ep1.adtrafficquality.google;
      font-src 'self';
    """
