# Netlify configuration file for MIDI Drum Remapper

[build]
  publish = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://cdn.skypack.dev;
      script-src 'self' 'unsafe-inline' 'unsafe-eval'
        https://cdn.skypack.dev
        https://pagead2.googlesyndication.com
        https://www.googletagmanager.com
        https://www.google-analytics.com
        https://www.googletagservices.com
        https://securepubads.g.doubleclick.net
        https://ep2.adtrafficquality.google;
      style-src 'self' 'unsafe-inline';
      connect-src 'self'
        https://www.google-analytics.com
        https://pagead2.googlesyndication.com
        https://tpc.googlesyndication.com
        https://securepubads.g.doubleclick.net
        https://ep1.adtrafficquality.google
        https://ep2.adtrafficquality.google;
      frame-src 'self'
        https://googleads.g.doubleclick.net
        https://tpc.googlesyndication.com
        https://securepubads.g.doubleclick.net
        https://www.google.com
        https://ep2.adtrafficquality.google;
      img-src 'self' data:
        https://pagead2.googlesyndication.com
        https://googleads.g.doubleclick.net
        https://www.google-analytics.com
        https://ep1.adtrafficquality.google
        https://www.googletagmanager.com
        https://tpc.googlesyndication.com
        https://securepubads.g.doubleclick.net;
      font-src 'self';
    """