# Netlify configuration file for MIDI Drum Remapper
# This file provides build settings and redirects for proper SPA routing

[build]
  # Since this is a static site, no build command is needed
  # The publish directory is the root of our project
  publish = "/"

# Handle 404 errors correctly by redirecting to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add security headers
[[headers]]
  # Define for all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://cdn.skypack.dev; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://cdn.skypack.dev https://pagead2.googlesyndication.com https://www.googletagmanager.com https://www.googletagservices.com https://ep2.adtrafficquality.google; img-src 'self' data:; font-src 'self'; connect-src 'self' https://www.google-analytics.com https://ep1.adtrafficquality.google https://pagead2.googlesyndication.com https://tpc.googlesyndication.com; frame-src 'self' https://googleads.g.doubleclick.net https://tpc.googlesyndication.com;"
